application: notes
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /res
  static_dir: static

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest