application: notes
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /res
  static_dir: static

- url: /note/(list|create|update|delete|move)/(.*)
  script: main.application
  
  
- url: /.*
  script: main.application
  login: required

libraries:
- name: jinja2
  version: latest